services:
  citizen-cab-svc:
    build: .
    container_name: citizen-cab-svc
    environment:
      - KV_VIPER_FILE=./config_docker.yaml
    ports:
      - "8002:8000"
    networks:
      - chains-net

  citizen-cab-postgres:
    image: postgres:15
    container_name:  citizen-cab-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chains-net

volumes:
  pgdata:
  bundle:

networks:
  chains-net:
    external: true
